/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author User
 */
public class bantuan extends javax.swing.JFrame {

    /**
     * Creates new form bantuan
     */
    public bantuan() {
        initComponents();
                        
        menu.setBackground(new Color(0, 0, 0, 40));
        button.setBackground(new Color(0, 0, 0, 40));
    }
    
    public void rKambingListener(ActionListener a){
        btnRKambing.addActionListener(a);
    }
    
    public void keluarListener(ActionListener a){
        btnKeluar.addActionListener(a);
    }
    
    public void tambahListener(ActionListener a){
        btnTambah.addActionListener(a);
    }
    
    public void kalkulatorListener(ActionListener a){
        btnKalkulator.addActionListener(a);
    }
    
    public void bantuanListener(ActionListener a){
        btnBantuan.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alas = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        btnRKambing = new javax.swing.JButton();
        btnKalkulator = new javax.swing.JButton();
        btnBantuan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        button = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1170, 660));
        setResizable(false);

        alas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("SISTEM INFORMASI PENITIPAN HEWAN TERNAK");
        judul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        alas.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        btnRKambing.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRKambing.setForeground(new java.awt.Color(255, 255, 255));
        btnRKambing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/kambing.png"))); // NOI18N
        btnRKambing.setText("Recording Kambing");
        btnRKambing.setContentAreaFilled(false);
        btnRKambing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRKambing.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alas.add(btnRKambing, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, -1));

        btnKalkulator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKalkulator.setForeground(new java.awt.Color(255, 255, 255));
        btnKalkulator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/kalkulator.png"))); // NOI18N
        btnKalkulator.setText("Kalkulator");
        btnKalkulator.setContentAreaFilled(false);
        btnKalkulator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKalkulator.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alas.add(btnKalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 155, -1));

        btnBantuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBantuan.setForeground(new java.awt.Color(255, 255, 255));
        btnBantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/help.png"))); // NOI18N
        btnBantuan.setText("Bantuan");
        btnBantuan.setContentAreaFilled(false);
        btnBantuan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBantuan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alas.add(btnBantuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 155, -1));

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/exit.png"))); // NOI18N
        btnKeluar.setContentAreaFilled(false);
        alas.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 155, 70));

        menu.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        alas.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, 460));

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setContentAreaFilled(false);
        alas.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 120, -1));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setContentAreaFilled(false);
        alas.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 120, -1));

        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/edit.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setContentAreaFilled(false);
        alas.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 120, -1));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/Save.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setContentAreaFilled(false);
        alas.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 120, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setContentAreaFilled(false);
        alas.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, 120, -1));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/Print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setContentAreaFilled(false);
        alas.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 120, -1));

        button.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout buttonLayout = new javax.swing.GroupLayout(button);
        button.setLayout(buttonLayout);
        buttonLayout.setHorizontalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        buttonLayout.setVerticalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        alas.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 770, 38));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/assets/background.jpg"))); // NOI18N
        alas.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bantuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alas;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBantuan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKalkulator;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRKambing;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel button;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
