/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
                        
        menu.setBackground(new Color(0, 0, 0, 40));
        kalkulator.setBackground(new Color(0, 0, 0, 40));
        result.setBackground(new Color(0, 0, 0, 40));
    }

    //<editor-fold defaultstate="collapse" desc="ACTION LISTENER">
    public void accountListener(ActionListener a) {
        btnAccount.addActionListener(a);
    }

    public void rAnimalListener(ActionListener a) {
        btnRAnimal.addActionListener(a);
    }

    public void tAnimalListener(ActionListener a) {
        btnTAnimal.addActionListener(a);
    }

    public void calculatorListener(ActionListener a) {
        btnCalculator.addActionListener(a);
    }

    public void logoutListener(ActionListener a) {
        btnLogout.addActionListener(a);
    }
        public void countListener(ActionListener a){
        btnCount.addActionListener(a);
    }
    //</editor-fold>
    
    
    //<editor-fold defaultstate="collapse" desc="GET">
    public String getGender(){
        return cmbGender.getSelectedItem().toString();
    }
    
    public String getAge(){
        return txtAge.getText();
    }
    
    public String getChestSize(){
        return txtChestSize.getText();
    }
    
    public String getBodyLength(){
        return txtBodyLength.getText();
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapse" desc="SET">    
    public void setMessage(String pesan) {
        this.message.setText(pesan);
    }

    public void setTxtPrice(String txtHarga) {
        this.txtPrice.setText(txtHarga);
    }

    public void setTxtTitleResult(String txtJudulHasil) {
        this.txtTitleResult.setText(txtJudulHasil);
    }

    public void setTxtWeight(String txtLD) {
        this.txtWeight.setText(txtLD);
    }
    
    public void setBgTitleResult(Color a){        
        this.txtTitleResult.setBackground(a);
    }
    
    public void setBgWeigth(Color a){        
        this.txtWeight.setBackground(a);
    }
    
    public void setBgPrice(Color a){        
        this.txtPrice.setBackground(a);
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        kalkulator = new javax.swing.JPanel();
        gender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        age = new javax.swing.JLabel();
        txtAge = new javax.swing.JFormattedTextField();
        years = new javax.swing.JLabel();
        bodyLength = new javax.swing.JLabel();
        txtBodyLength = new javax.swing.JFormattedTextField();
        cm1 = new javax.swing.JLabel();
        chestSize = new javax.swing.JLabel();
        txtChestSize = new javax.swing.JFormattedTextField();
        cm2 = new javax.swing.JLabel();
        btnCount = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        result = new javax.swing.JPanel();
        txtTitleResult = new javax.swing.JLabel();
        txtWeight = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        btnRAnimal = new javax.swing.JButton();
        btnTAnimal = new javax.swing.JButton();
        btnCalculator = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("SISTEM INFORMASI PENITIPAN HEWAN TERNAK");
        judul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        kalkulator.setBackground(new java.awt.Color(153, 153, 153));
        kalkulator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("gender");
        kalkulator.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Jantan", "Betina" }));
        kalkulator.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("Age");
        kalkulator.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        kalkulator.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 38, -1));

        years.setForeground(new java.awt.Color(255, 255, 255));
        years.setText("Years");
        kalkulator.add(years, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 10));

        bodyLength.setForeground(new java.awt.Color(255, 255, 255));
        bodyLength.setText("Body Length");
        kalkulator.add(bodyLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        kalkulator.add(txtBodyLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 37, -1));

        cm1.setForeground(new java.awt.Color(255, 255, 255));
        cm1.setText("cm");
        kalkulator.add(cm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 10));

        chestSize.setForeground(new java.awt.Color(255, 255, 255));
        chestSize.setText("Chest Size");
        kalkulator.add(chestSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        kalkulator.add(txtChestSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 39, -1));

        cm2.setForeground(new java.awt.Color(255, 255, 255));
        cm2.setText("cm");
        kalkulator.add(cm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 10));

        btnCount.setText("Count");
        kalkulator.add(btnCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 190, 200, -1));

        jPanel.add(kalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 260, 250));

        message.setForeground(new java.awt.Color(204, 0, 0));
        jPanel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 230, 20));

        result.setBackground(new java.awt.Color(153, 153, 153));

        txtTitleResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTitleResult.setForeground(new java.awt.Color(255, 255, 255));
        txtTitleResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtWeight.setForeground(new java.awt.Color(255, 255, 255));

        txtPrice.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout resultLayout = new javax.swing.GroupLayout(result);
        result.setLayout(resultLayout);
        resultLayout.setHorizontalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTitleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(resultLayout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        resultLayout.setVerticalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtTitleResult, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 460, 150));

        btnAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_crowd_50px.png"))); // NOI18N
        btnAccount.setText("Account");
        btnAccount.setContentAreaFilled(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, 80));

        btnRAnimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnRAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_Pet_Commands_Summon_50px.png"))); // NOI18N
        btnRAnimal.setText("Recording Animal");
        btnRAnimal.setContentAreaFilled(false);
        btnRAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnRAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 155, 80));

        btnTAnimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnTAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_Pet_Commands_Summon_50px_1.png"))); // NOI18N
        btnTAnimal.setText("Type Animal");
        btnTAnimal.setContentAreaFilled(false);
        btnTAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnTAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 155, 80));

        btnCalculator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalculator.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_calculator_48px_1.png"))); // NOI18N
        btnCalculator.setText("Calculator");
        btnCalculator.setContentAreaFilled(false);
        btnCalculator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalculator.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 155, 80));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_exit_32px_1.png"))); // NOI18N
        btnLogout.setText("LogOut");
        btnLogout.setContentAreaFilled(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 155, 60));

        menu.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, 380));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/assets/background.jpg"))); // NOI18N
        jPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bodyLength;
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCalculator;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRAnimal;
    private javax.swing.JButton btnTAnimal;
    private javax.swing.JLabel chestSize;
    private javax.swing.JLabel cm1;
    private javax.swing.JLabel cm2;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel gender;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel kalkulator;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel message;
    private javax.swing.JPanel result;
    private javax.swing.JFormattedTextField txtAge;
    private javax.swing.JFormattedTextField txtBodyLength;
    private javax.swing.JFormattedTextField txtChestSize;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtTitleResult;
    private javax.swing.JLabel txtWeight;
    private javax.swing.JLabel years;
    // End of variables declaration//GEN-END:variables
}
