/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public kalkulator() {
        initComponents();
                        
        menu.setBackground(new Color(0, 0, 0, 40));
        button.setBackground(new Color(0, 0, 0, 40));
        kalkulator.setBackground(new Color(0, 0, 0, 40));
        hasil.setBackground(new Color(0, 0, 0, 40));
    }

    public void rKambingListener(ActionListener a){
        btnRKambing.addActionListener(a);
    }
    
    public void keluarListener(ActionListener a){
        btnKeluar.addActionListener(a);
    }
    
    public void tambahListener(ActionListener a){
        btnTambah.addActionListener(a);
    }
    
    public void kalkulatorListener(ActionListener a){
        btnKalkulator.addActionListener(a);
    }
    
    public void bantuanListener(ActionListener a){
        btnBantuan.addActionListener(a);
    }
    
    public String getJenisKelamin(){
        return cmbJK.getSelectedItem().toString();
    }
    
    public String getUsia(){
        return txtUsia.getText();
    }
    
    public String getLD(){
        return txtLD.getText();
    }
    
    public String getPB(){
        return txtPB.getText();
    }
    
    public void hitungListener(ActionListener a){
        btnHitung.addActionListener(a);
    }

    public void setPesan(String pesan) {
        this.pesan.setText(pesan);
    }

    public void setTxtHarga(String txtHarga) {
        this.txtHarga.setText(txtHarga);
    }

    public void setTxtJudulHasil(String txtJudulHasil) {
        this.txtJudulHasil.setText(txtJudulHasil);
    }

    public void setTxtBB(String txtLD) {
        this.txtBB.setText(txtLD);
    }
    
    public void setBgJudulHasil(Color a){        
        this.txtJudulHasil.setBackground(a);
    }
    
    public void setBgBB(Color a){        
        this.txtBB.setBackground(a);
    }
    
    public void setBgHarga(Color a){        
        this.txtHarga.setBackground(a);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alas = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        btnRKambing = new javax.swing.JButton();
        btnKalkulator = new javax.swing.JButton();
        btnBantuan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        button = new javax.swing.JPanel();
        kalkulator = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbJK = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLD = new javax.swing.JFormattedTextField();
        txtPB = new javax.swing.JFormattedTextField();
        txtUsia = new javax.swing.JFormattedTextField();
        btnHitung = new javax.swing.JButton();
        txtJudulHasil = new javax.swing.JLabel();
        txtBB = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        pesan = new javax.swing.JLabel();
        hasil = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1170, 660));
        setResizable(false);

        alas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("SISTEM INFORMASI PENITIPAN HEWAN TERNAK");
        judul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        alas.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        btnRKambing.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRKambing.setForeground(new java.awt.Color(255, 255, 255));
        btnRKambing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/kambing.png"))); // NOI18N
        btnRKambing.setText("Recording Kambing");
        btnRKambing.setContentAreaFilled(false);
        btnRKambing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRKambing.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alas.add(btnRKambing, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, -1));

        btnKalkulator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKalkulator.setForeground(new java.awt.Color(255, 255, 255));
        btnKalkulator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/kalkulator.png"))); // NOI18N
        btnKalkulator.setText("Kalkulator");
        btnKalkulator.setContentAreaFilled(false);
        btnKalkulator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKalkulator.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alas.add(btnKalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 155, -1));

        btnBantuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBantuan.setForeground(new java.awt.Color(255, 255, 255));
        btnBantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/help.png"))); // NOI18N
        btnBantuan.setText("Bantuan");
        btnBantuan.setContentAreaFilled(false);
        btnBantuan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBantuan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alas.add(btnBantuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 155, -1));

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/exit.png"))); // NOI18N
        btnKeluar.setContentAreaFilled(false);
        alas.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 155, 70));

        menu.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        alas.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, 460));

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setContentAreaFilled(false);
        alas.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 120, -1));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setContentAreaFilled(false);
        alas.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 120, -1));

        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/edit.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setContentAreaFilled(false);
        alas.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 120, -1));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/Save.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setContentAreaFilled(false);
        alas.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 120, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setContentAreaFilled(false);
        alas.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, 120, -1));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/Print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setContentAreaFilled(false);
        alas.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, 120, -1));

        button.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout buttonLayout = new javax.swing.GroupLayout(button);
        button.setLayout(buttonLayout);
        buttonLayout.setHorizontalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        buttonLayout.setVerticalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        alas.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 770, 38));

        kalkulator.setBackground(new java.awt.Color(153, 153, 153));
        kalkulator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lingkar Dada");
        kalkulator.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("cm");
        kalkulator.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 10));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tahun");
        kalkulator.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 10));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usia");
        kalkulator.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("cm");
        kalkulator.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 10));

        cmbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Jantan", "Betina" }));
        kalkulator.add(cmbJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Kelamin");
        kalkulator.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Panjang Badan");
        kalkulator.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        kalkulator.add(txtLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 39, -1));
        kalkulator.add(txtPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 37, -1));
        kalkulator.add(txtUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 38, -1));

        btnHitung.setText("Hitung");
        kalkulator.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 190, 200, -1));

        alas.add(kalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 260, 250));

        txtJudulHasil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtJudulHasil.setForeground(new java.awt.Color(255, 255, 255));
        txtJudulHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alas.add(txtJudulHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 410, 410, 28));

        txtBB.setForeground(new java.awt.Color(255, 255, 255));
        alas.add(txtBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 200, 29));

        txtHarga.setForeground(new java.awt.Color(255, 255, 255));
        alas.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 200, 29));

        pesan.setForeground(new java.awt.Color(204, 0, 0));
        alas.add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 230, 20));

        hasil.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout hasilLayout = new javax.swing.GroupLayout(hasil);
        hasil.setLayout(hasilLayout);
        hasilLayout.setHorizontalGroup(
            hasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        hasilLayout.setVerticalGroup(
            hasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        alas.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 460, 150));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/assets/background.jpg"))); // NOI18N
        alas.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alas;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBantuan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKalkulator;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRKambing;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel button;
    private javax.swing.JComboBox<String> cmbJK;
    private javax.swing.JPanel hasil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel kalkulator;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel pesan;
    private javax.swing.JLabel txtBB;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtJudulHasil;
    private javax.swing.JFormattedTextField txtLD;
    private javax.swing.JFormattedTextField txtPB;
    private javax.swing.JFormattedTextField txtUsia;
    // End of variables declaration//GEN-END:variables
}
