/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class v_calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public v_calculator() {
        initComponents();
                        
        menu.setBackground(new Color(0, 0, 0, 40));
        calculator.setBackground(new Color(0, 0, 0, 40));
        result.setBackground(new Color(0, 0, 0, 40));
    }

    //<editor-fold defaultstate="collapse" desc="ACTION LISTENER">
    public void profilListener(ActionListener a) {
        btnProfil.addActionListener(a);
    }

    public void rAnimalListener(ActionListener a) {
        btnRAnimal.addActionListener(a);
    }

    public void animalCareListener(ActionListener a) {
        btnAnimalCare.addActionListener(a);
    }

    public void calculatorListener(ActionListener a) {
        btnCalculator.addActionListener(a);
    }

    public void logoutListener(ActionListener a) {
        btnLogout.addActionListener(a);
    }
        public void countListener(ActionListener a){
        btnCount.addActionListener(a);
    }
    //</editor-fold>
        
    //<editor-fold defaultstate="collapse" desc="GET">
    public String getGender(){
        return cmbGender.getSelectedItem().toString();
    }
    
    public String getAge(){
        return txtAge.getText();
    }
    
    public String getChestSize(){
        return txtChestSize.getText();
    }
    
    public String getBodyLength(){
        return txtBodyLength.getText();
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapse" desc="SET">    
    public void setMessage(String message) {
        this.message.setText(message);
    }

    public void setTxtPrice(String txtPrice) {
        this.txtPrice.setText(txtPrice);
    }

    public void setTxtTitleResult(String txtResultTitle) {
        this.txtTitleResult.setText(txtResultTitle);
    }

    public void setTxtWeight(String txtWeight) {
        this.txtWeight.setText(txtWeight);
    }
    
    public void setBgTitleResult(Color a){        
        this.txtTitleResult.setBackground(a);
    }
    
    public void setBgWeigth(Color a){        
        this.txtWeight.setBackground(a);
    }
    
    public void setBgPrice(Color a){        
        this.txtPrice.setBackground(a);
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        calculator = new javax.swing.JPanel();
        gender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        age = new javax.swing.JLabel();
        txtAge = new javax.swing.JFormattedTextField();
        years = new javax.swing.JLabel();
        bodyLength = new javax.swing.JLabel();
        txtBodyLength = new javax.swing.JFormattedTextField();
        cm1 = new javax.swing.JLabel();
        chestSize = new javax.swing.JLabel();
        txtChestSize = new javax.swing.JFormattedTextField();
        cm2 = new javax.swing.JLabel();
        btnCount = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        txtTitleResult = new javax.swing.JLabel();
        txtWeight = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        result = new javax.swing.JPanel();
        btnProfil = new javax.swing.JButton();
        btnRAnimal = new javax.swing.JButton();
        btnAnimalCare = new javax.swing.JButton();
        btnCalculator = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/title.png"))); // NOI18N
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        calculator.setBackground(new java.awt.Color(153, 153, 153));
        calculator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("gender");
        calculator.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Male", "Female" }));
        cmbGender.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculator.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("Age");
        calculator.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        calculator.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 38, -1));

        years.setForeground(new java.awt.Color(255, 255, 255));
        years.setText("Years");
        calculator.add(years, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 10));

        bodyLength.setForeground(new java.awt.Color(255, 255, 255));
        bodyLength.setText("Body Length");
        calculator.add(bodyLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        calculator.add(txtBodyLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 37, -1));

        cm1.setForeground(new java.awt.Color(255, 255, 255));
        cm1.setText("cm");
        calculator.add(cm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 10));

        chestSize.setForeground(new java.awt.Color(255, 255, 255));
        chestSize.setText("Chest Size");
        calculator.add(chestSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        calculator.add(txtChestSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 39, -1));

        cm2.setForeground(new java.awt.Color(255, 255, 255));
        cm2.setText("cm");
        calculator.add(cm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 10));

        btnCount.setText("Count");
        btnCount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculator.add(btnCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 190, 200, -1));

        jPanel.add(calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 260, 250));

        message.setForeground(new java.awt.Color(204, 0, 0));
        jPanel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 230, 20));

        txtTitleResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTitleResult.setForeground(new java.awt.Color(255, 255, 255));
        txtTitleResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel.add(txtTitleResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 410, 28));

        txtWeight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(255, 255, 255));
        jPanel.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 200, 29));

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 200, 29));

        result.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout resultLayout = new javax.swing.GroupLayout(result);
        result.setLayout(resultLayout);
        resultLayout.setHorizontalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        resultLayout.setVerticalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 460, 150));

        btnProfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProfil.setForeground(new java.awt.Color(255, 255, 255));
        btnProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_nurse_male_30px.png"))); // NOI18N
        btnProfil.setText("Profil");
        btnProfil.setContentAreaFilled(false);
        btnProfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, 80));

        btnRAnimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnRAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_Pet_Commands_Summon_50px.png"))); // NOI18N
        btnRAnimal.setText("Recording Animal");
        btnRAnimal.setContentAreaFilled(false);
        btnRAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnRAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 155, 80));

        btnAnimalCare.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAnimalCare.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimalCare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_Pet_Commands_Summon_50px_1.png"))); // NOI18N
        btnAnimalCare.setText("Animal Care");
        btnAnimalCare.setContentAreaFilled(false);
        btnAnimalCare.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnimalCare.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnAnimalCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 155, 80));

        btnCalculator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalculator.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_calculator_48px_1.png"))); // NOI18N
        btnCalculator.setText("Calculator");
        btnCalculator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalculator.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 155, 80));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/icons8_exit_32px_1.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setContentAreaFilled(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 155, 60));

        menu.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, 380));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/assets/background.jpg"))); // NOI18N
        jPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bodyLength;
    private javax.swing.JButton btnAnimalCare;
    private javax.swing.JButton btnCalculator;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnRAnimal;
    private javax.swing.JPanel calculator;
    private javax.swing.JLabel chestSize;
    private javax.swing.JLabel cm1;
    private javax.swing.JLabel cm2;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel gender;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel message;
    private javax.swing.JPanel result;
    private javax.swing.JLabel title;
    private javax.swing.JFormattedTextField txtAge;
    private javax.swing.JFormattedTextField txtBodyLength;
    private javax.swing.JFormattedTextField txtChestSize;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtTitleResult;
    private javax.swing.JLabel txtWeight;
    private javax.swing.JLabel years;
    // End of variables declaration//GEN-END:variables
}
