/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author zha
 */
public class V_login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public V_login() {
        initComponents();
    }

    public JLabel getAlertMessage() {
        return alertMessage;
    }

    public void setAlertMessage(String alertMessage) {
        this.alertMessage.setText(alertMessage);
    }

    public JTextField getTf_email() {
        return tf_email;
    }

    public void setTf_email(JTextField tf_email) {
        this.tf_email = tf_email;
    }

    public JTextField getTf_password() {
        return tf_password;
    }

    public void setTf_password(JTextField tf_password) {
        this.tf_password = tf_password;
    }
    
    public void ClickLogin(ActionListener action) {
        btn_login.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_email = new javax.swing.JTextField();
        tf_password = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        alertMessage = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, -1));
        getContentPane().add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, -1));

        btn_login.setText("login");
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        getContentPane().add(alertMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 180, 20));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 0, 326, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertMessage;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_login;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_password;
    // End of variables declaration//GEN-END:variables
}
