/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;

/**
 *
 * @author zha
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public String JK;
    public double usia, pb, ld;

    public String getJK() {
        return JK;
    }

    public void setJK(String JK) {
        this.JK = JK;
    }

    public double getUsia() {
        return usia;
    }

    public void setUsia(double usia) {
        this.usia = usia;
    }

    public double getPb() {
        return pb;
    }

    public void setPb(double pb) {
        this.pb = pb;
    }

    public double getLd() {
        return ld;
    }

    public void setLd(double ld) {
        this.ld = ld;
    }

    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbJK = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsia = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPB = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLD = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtJudulHasil = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtBB = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        pesan = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Hewan Ternak Kambing");
        setPreferredSize(new java.awt.Dimension(600, 250));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Kelamin :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        cmbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Jantan", "Betina" }));
        jPanel1.add(cmbJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usia :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tahun");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 10));
        jPanel1.add(txtUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 38, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Panjang Badan :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel1.add(txtPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 37, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("cm");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 10));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lingkar Dada :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(txtLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 39, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("cm");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 10));

        txtJudulHasil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtJudulHasil.setForeground(new java.awt.Color(255, 255, 255));
        txtJudulHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtJudulHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 200, 28));

        txtHarga.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 200, 29));

        txtBB.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 29));

        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, -1));
        jPanel1.add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 580, 30));

        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/farm-min.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 275));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        if (txtLD.getText().equals("") && txtPB.getText().equals("") &&
            txtUsia.getText().equals("") && cmbJK.getSelectedIndex() == 0) {
            pesan.setText("LENGKAPI DATA!!!");
            txtJudulHasil.setText("");
            txtBB.setText("");
            txtHarga.setText("");
            pesan.setForeground(Color.red);
        } else {
            pesan.setText("");
            txtJudulHasil.setText("HASIL");
            setLd(Double.parseDouble(txtLD.getText()));
            setPb(Double.parseDouble(txtPB.getText()));
            double hasil = (2 * getLd() * getPb()) / 104;
            txtBB.setText("Berat Badan = " + String.valueOf(hasil));
            int harga;
            if (cmbJK.getSelectedIndex() == 1) {
                harga = (int) (hasil * 30000) + 200000;
                txtHarga.setText("Harga = Rp. "+harga);
            } else {
                harga = (int) (hasil * 30000);
                txtHarga.setText("Harga = Rp. "+harga);
            }
            
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cmbJK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pesan;
    private javax.swing.JLabel txtBB;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtJudulHasil;
    private javax.swing.JFormattedTextField txtLD;
    private javax.swing.JFormattedTextField txtPB;
    private javax.swing.JFormattedTextField txtUsia;
    // End of variables declaration//GEN-END:variables
}
